version: "3.8"

# docker run --name daily-manager -p 3001:3001 -v "${PWD}":/app daily-manager_image

services:
  daily-manager:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
    container_name: daily-manager
    image: daily-manager_image
